version: '3.8'

services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /usr/app/src

    command: bash -c 'python bot/run.py'
    networks:
      - habit_network

networks:
  habit_network:
    external: true
    name: habit_network